name: Deploy Next.js with Dockerfile

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate .env.staging
        run: |
          echo "NEXT_PUBLIC_ENV=${{ secrets.NEXT_PUBLIC_ENV }}" >> .env.staging
          echo "NEXT_PUBLIC_EMAIL=${{ secrets.NEXT_PUBLIC_EMAIL }}" >> .env.staging
          echo "NEXT_PUBLIC_PHONE_NUMBER=${{ secrets.NEXT_PUBLIC_PHONE_NUMBER }}" >> .env.staging
          echo "NEXT_PUBLIC_WEBSITE=${{ secrets.NEXT_PUBLIC_WEBSITE }}" >> .env.staging
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env.staging
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env.staging
          echo "NEXT_PUBLIC_FIREBASE_PROJECTID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECTID }}" >> .env.staging
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env.staging
          echo "NEXT_PUBLIC_FIREBASE_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_SENDER_ID }}" >> .env.staging
          echo "NEXT_PUBLIC_FIREBASE_APIID=${{ secrets.NEXT_PUBLIC_FIREBASE_APIID }}" >> .env.staging
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENTID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENTID }}" >> .env.staging

      - name: Build Docker image with staging env
        run: docker build --build-arg ENV_FILE=.env.staging -t nextjs-app .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Image to Docker Hub
        run: |
          docker tag nextjs-app ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

      - name: Pull image on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 30m 
          script: |
            sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

      - name: Run container on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 5m
          script: |
            sudo docker stop nextjs-app || true
            sudo docker rm nextjs-app || true
            sudo docker run -d --name nextjs-app -p 5000:3000 ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

